name: barcode_image
description: >-
  Barcode generation library for Dart that can generate
  barcodes using the image library.
_author: David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/DavBfr/dart_barcode/tree/master/image
repository: https://github.com/DavBfr/dart_barcode
issue_tracker: https://github.com/DavBfr/dart_barcode/issues
version: 2.0.3

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  args: ^2.7.0
  #barcode: ^2.2.9
  barcode:
    git:
      url: git@github.com:angcyo/dart_barcode.git
      path: barcode
      ref: 2.2.9-fix1
  image: ^4.9.1
  meta: any

dependency_overrides:
  barcode:
    path: ../barcode

dev_dependencies:
  build_runner: ^2.15.0
  crypto: ^3.0.7
  flutter_lints: ^6.0.0
  pubspec_extract: ^2.1.1
  test: ^1.31.1

executables:
  barcode:

pubspec_extract:
  destination: lib/src/pubspec.dart
